from typing import Dict, Any
from app.services.llm_service import llm_service
from datetime import datetime

class ReportGeneratorService:
    @staticmethod
    def generate_markdown_report(data: Dict[str, Any]) -> str:
        """
        Takes raw json data of insights, forecasts, or automl results
        and compiles it into a beautiful Markdown Executive Report using the LLM.
        """
        
        system_prompt = f"""
        You are an elite Data Science Executive communicating to the C-Suite.
        You have been provided with analytical data from the AntiGravity platform.
        Your goal is to synthesize this data into a professional, highly readable Executive Summary in Markdown format.
        
        The report should include:
        1. An attention-grabbing title.
        2. Date of generation.
        3. Executive Summary (High-level takeaways).
        4. Key Findings (Bullet points based on the data provided).
        5. Strategic Recommendations based on the findings.
        
        Here is the raw JSON data to analyze:
        {data}
        
        Format the output exclusively in Markdown. Do not include introductory text like "Here is the report".
        """
        
        try:
            markdown_report = llm_service.llm.invoke(system_prompt).content
        except Exception as e:
            # Fallback if LLM is unavailable
            markdown_report = f"""
# AntiGravity Executive Report
*Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*

## Executive Summary
This is an automated fallback report generated by the AntiGravity Platform. The advanced AI synthesis engine is currently unavailable due to missing API keys.

## Raw Data Snapshot
```json
{data}
```

## Strategic Recommendations
- Connect a valid LLM API key to generate detailed, synthesized executive summaries.
- Review the raw data snapshot above to understand the current state of the analysis.
"""
        return markdown_report
